### PR TITLE
first working parallelization

### PR DESCRIPTION
**Pull request by danitrod**

### CODE REVIEW

**Comment by danitrod** [comment]
Sorry, meant to PR to my fork 😅

**Comment by paulgb** [comment]
😀 no worries. Would love to know what sort of speed up you get from it when it’s done!

**Comment by danitrod** [comment]
Happy to share with you -- currently a speedup of around 10x for some grid setups, when running with 16 threads! :D

I'll better structure the results in the future. To give a little bit of context, I am a last semester CS student and am studying WASM + Web Workers for my undergrad thesis. I found this application and thought it would be fun to parallelize it, which has proven to work out pretty nicely from my tests. 

For now the approach is to simply have each thread use a different subset of possible words for the first word, and solve the rest of the problem normally. I'm currently studying what other approaches can be used, but already have those nice results :) 

I'll keep you up to date on my studies if you're interested!

**Comment by paulgb** [comment]
Awesome! I'd been wondering if it was possible to parallelize it. Would be glad to see more about your approach!

**Pull request closed without merging**
